### PR TITLE
Async all the things

### PR DESCRIPTION
**Pull request by xrmx**
Using axios instead of request which was deprecated in february 2020

### CODE REVIEW

**Comment by matjack1** [comment]
nice!

In general you should leave the package-lock file as otherwise you will end up using different versions compared to what is intended/supported by the developer

**Comment by xrmx** [comment]
Forgot to commit i guess

**Comment by xrmx** [comment]
@matjack1 what do you mean by leave? package-lock is committed

**Comment by matjack1** [comment]
lol sorry, seemed like you were deleting it! My fault, merging!

**Pull request merged**
